### ISSUE TITLE
[stattrack] status command drops to 0 in metrics upon update/reloading the cog.

### ISSUE THREAD

**Issue by Skyridr** [Vexed01/Vex-Cogs#71] opened 2022-01-08 21:35 UTC
### What cog is this bug report for?

stattrack

### What versions are you running?

               Your Version    Latest version    Up to date?
-------------  --------------  ----------------  -------------
This Cog       1.8.0           1.8.0             🟢
Bundled Utils  0c6bf04         0c6bf04           🟢
Red            3.4.13          3.4.16            🔴

### Describe the bug

I just updated to 1.8.0, and checked the status metrics (all). And I noticed a drop to 0 due to I assume the update / reload of the cog:

![image](https://user-images.githubusercontent.com/6794064/148660764-9bf8391b-1f96-4a8b-a99e-e83fa04d83f2.png)

Not sure if this is intended as I am not sure if it should use previous data (or skip the missing data on the metrics) before the reload. Making a issue about it just in case.

**Comment by Vexed01** [comment] 2022-01-08 22:15
That's really odd. It didn't happen to me. It appears to non-smoothly increase which suggests it's a data issue and not a cog issue.

The intended behaviour is that there would be a gap in the graph.

Maybe take a look at `[p]stattrack status 2h` to see this section in more detail? If it is a gradual increase then it's something wrong with the data which I can't set on my end. I could also take a look at `[p]stattrack export json` if you are happy to share it so I can take a further look, though this would be tomorrow (UTC+0).

**Comment by Skyridr** [comment] 2022-01-09 15:43
Sorry about the delay. I posted this when I was heading to bed. You are right, this was an issue on a single bot. I'm running the exact same cog on the same server on a different bot, and that has no data "corruption" so to speak.

Here's the data of 8 hours ago (when I ran the command this morning before I was heading to work):

![image](https://user-images.githubusercontent.com/6794064/148689433-b5d6feb3-1c3b-4b81-8141-a39108ffb29f.png)

And running (all) on my second bot:

![image](https://user-images.githubusercontent.com/6794064/148689437-04ffdf8e-000c-4e20-b9fa-6bb45e16536c.png)

Don't ask me why I'm running the same cog on a different bot :p. Maybe I found it useful to check out RED's process information on each bot.

Here's the json file (I've changed the file extension from json to log as github was refusing json files).

[stattrack.log](https://github.com/Vexed01/Vex-Cogs/files/7835360/stattrack.log)

Hope it's useful!

**Comment by Vexed01** [comment] 2022-01-09 16:53
That's for providing further details.

Looking at the export, what happened is that you updated around 20:10/20:11 and then the counts fell at 20:12.
Between 20:11 and 20:12, your total user count remained constant. As you can see in the graph, the online/idle/dnd user counts dropped to almost zero. It seems for whatever reason all these users went to being offline, as offline jumped from 15**1655** to 15**6417**, which is a difference around the same as the total online/idle/dnd before. All the other statistics in the export look normal.

I'm not sure what caused this, so I'm afraid I'll have to close the issue. I haven't been able to reproduce this myself either.

Hopefully it won't happen again...

**Closed by Vexed01** 2022-01-09 16:53 UTC
Labels: type: bug, cog: stattrack

**Comment by Skyridr** [comment] 2022-01-15 14:13
It seems to have happened 2 more times over thee past few days:

https://media.discordapp.net/attachments/849473399213916190/931913665215594526/plot.png?width=720&height=450
